version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:
    pre_build:
      - pip install -r requirements_dev.txt
      - pip install .
      - cd docs && sphinx-apidoc -o . ../irase_data_manager --force && make html


python:
  install:
    - requirements: requirements.txt
    - path: .

sphinx:
  configuration: docs/conf.py
